language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=1.6.1
  - DJANGO=1.6.2

install:
  - pip install -r requirements.txt
  - pip install -q Django=$DJANGO
  - python setup.py -q install

script:
  - python ./manage.py test
