language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.6.1
  - DJANGO_VERSION=1.6.2
  - DJANGO_VERSION=1.6.5
  - DJANGO_VERSION=1.6.6

install:
  - pip install -q Pillow
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

script:
  - python ./manage.py test
